--- 
catalog: 
  description: "Maniaplanet Dedicated server for Trackmania² and Shootmania games from Nadeo based on Emetophobic's images."
  minimum_rancher_version: v0.51.0
  name: "Maniaplanet Dedicated Server"
  questions: 
    - 
      default: server
      description: "Login from your server's masterserver account"
      label: "Masterserver Account Login"
      required: true
      type: string
      variable: masterserver_account_login
    - 
      default: secretpass
      description: "Password from your server's masterserver account"
      label: "Masterserver Account Password"
      required: true
      type: string
      variable: masterserver_account_password
    - 
      default: ABCDEF
      description: "Validation key from your maniaplanet account"
      label: "Masterserver Validation Key"
      required: true
      type: string
      variable: masterserver_account_validation_key
    - 
      default: "2350"
      description: "The port you want the server to run on"
      label: "Maniaplanet Server port"
      required: true
      type: int
      variable: server_port
    - 
      default: "5030"
      description: "Exposed port on the host machine"
      label: "Exposed Port"
      required: true
      type: int
      variable: exposed_port
    - 
      default: "5000"
      description: "Port for communicating to the XML-RPC module of the server"
      label: "XML-RPC Port"
      required: true
      type: int
      variable: xmlrpc_port
    - 
      default: SMStorm
      description: "Title pack to be used with the server"
      label: "Title Pack"
      options: 
        - SMStorm
        - TMCanyon
        - TMStadium
        - TMLagoon
        - TMValley
      required: true
      type: enum
      variable: title
  version: v1.0-emetophobic
services: 
  maniaplanet-server: 
    scale: 1
