name: 'ManiaPlanet Server'
description: |
  # Description of the Catalog Entry
version: 0
category: "Game servers"
maintainer: # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry