--- 
category: "Game servers"
description: "Maniaplanet Dedicated Server for Trackmania² and Shootmaia games from Nadeo. Based on Emetophobic's image"
license: ~
maintainer: ~
name: "ManiaPlanet Server"
projectURL: ~
version: 0
